"""Type stubs for lazy-loaded components."""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .components import (
        animated_image,
        animation,
        avatar,
        badge,
        breadcrumb,
        breadcrumb_item,
        button,
        button_group,
        callout,
        card,
        carousel,
        carousel_item,
        checkbox,
        color_picker,
        comparison,
        copy_button,
        details,
        dialog,
        divider,
        drawer,
        dropdown,
        dropdown_item,
        format_bytes,
        format_date,
        format_number,
        icon,
        include,
        input,
        intersection_observer,
        mutation_observer,
        option,
        popover,
        popup,
        progress_bar,
        progress_ring,
        qr_code,
        radio,
        radio_group,
        rating,
        relative_time,
        resize_observer,
        scroller,
        select,
        skeleton,
        slider,
        spinner,
        split_panel,
        switch,
        tab,
        tab_group,
        tab_panel,
        tag,
        textarea,
        tooltip,
        tree,
        tree_item,
        zoomable_frame,
    )


__all__: list[str]